server:
  port: 8251

spring:
  application:
    name: NOTIFICATION-SERVICE


  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: ProjectMS-ECom-Topic
    consumer:
      group-id: projectMsECom-groupId-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.learnMS.Notification.model.Order


  # services tracing using zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
    integration:
      enabled: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka